language: node_js
node_js: 13
branches:
  only:
  - master #or your source branch name
cache:
  directories:
  - node_modules #cache models to speed up the build
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo generate
after_success: #remember to change name, email address, etc.
- git config --global user.name "riiswa"
- git config --global user.email "wradji64@gmail.com"
- sed -i'' - sed -i'' "s~git@github.com:riiswa/riiswa.github.io.git~https://${REPO_TOKEN}@github.com/riiswa/riiswa.github.io.git~" _config.yml
- hexo d 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public